declare namespace Colame.Item.Data {
  export type IngredientData = {
    id: number | null;
    name: string;
    unit: string;
    costPerUnit: number;
    supplierId: number | null;
    storageRequirements: string | null;
    shelfLifeDays: number | null;
    currentStock: number;
    reorderLevel: number;
    reorderQuantity: number;
    isActive: boolean;
    createdAt: string | null;
    updatedAt: string | null;
    deletedAt: string | null;
  };
  export type InventoryAdjustmentData = {
    id: number | null;
    itemId: number;
    variantId: number | null;
    locationId: number | null;
    quantityChange: number;
    adjustmentType: string;
    reason: string;
    notes: string | null;
    beforeQuantity: number;
    afterQuantity: number;
    userId: number | null;
    createdAt: string | null;
  };
  export type InventoryMovementData = {
    id: number | null;
    inventoriableType: string;
    inventoriableId: number;
    locationId: number;
    movementType: string;
    quantity: number;
    unitCost: number | null;
    beforeQuantity: number;
    afterQuantity: number;
    referenceType: string | null;
    referenceId: string | null;
    reason: string | null;
    userId: number | null;
    createdAt: string | null;
  };
  export type InventoryTransferData = {
    id: number | null;
    itemId: number;
    variantId: number | null;
    fromLocationId: number;
    toLocationId: number;
    quantity: number;
    notes: string | null;
    status: string;
    transferId: string | null;
    initiatedBy: number | null;
    completedBy: number | null;
    initiatedAt: string | null;
    completedAt: string | null;
  };
  export type ItemData = {
    id: number | null;
    name: string;
    slug: string;
    description: string | null;
    sku: string | null;
    barcode: string | null;
    base_price: number | null;
    base_cost: number;
    preparation_time: number;
    is_active: boolean;
    is_available: boolean;
    is_featured: boolean;
    track_inventory: boolean;
    stock_quantity: number;
    low_stock_threshold: number;
    type: string;
    allergens: Array<any> | null;
    nutritional_info: Array<any> | null;
    sort_order: number;
    available_from: string | null;
    available_until: string | null;
    created_at: string | null;
    updated_at: string | null;
    deleted_at: string | null;
  };
  export type ItemImageData = {
    id: number | null;
    itemId: number;
    imagePath: string;
    thumbnailPath: string | null;
    altText: string | null;
    isPrimary: boolean;
    sortOrder: number;
    createdAt: string | null;
    updatedAt: string | null;
  };
  export type ItemLocationPriceData = {
    id: number | null;
    itemId: number;
    itemVariantId: number | null;
    locationId: number;
    price: number;
    currency: string;
    validFrom: string | null;
    validUntil: string | null;
    availableDays: Array<any> | null;
    availableFromTime: string | null;
    availableUntilTime: string | null;
    isActive: boolean;
    priority: number;
    createdAt: string | null;
    updatedAt: string | null;
  };
  export type ItemLocationStockData = {
    id: number | null;
    itemId: number;
    itemVariantId: number | null;
    locationId: number;
    quantity: number;
    reservedQuantity: number;
    reorderPoint: number;
    reorderQuantity: number;
    createdAt: string | null;
    updatedAt: string | null;
  };
  export type ItemModifierData = {
    id: number | null;
    modifierGroupId: number;
    name: string;
    priceAdjustment: number;
    maxQuantity: number;
    isDefault: boolean;
    isActive: boolean;
    sortOrder: number;
    createdAt: string | null;
    updatedAt: string | null;
  };
  export type ItemVariantData = {
    id: number | null;
    itemId: number;
    name: string;
    sku: string | null;
    priceAdjustment: number;
    sizeMultiplier: number;
    isDefault: boolean;
    isActive: boolean;
    stockQuantity: number;
    sortOrder: number;
    createdAt: string | null;
    updatedAt: string | null;
  };
  export type ItemWithRelationsData = {
    item: Colame.Item.Data.ItemData;
    variants: Array<any> | null;
    modifierGroups: Array<any> | null;
    images: Array<any> | null;
    categories: Array<any> | null;
    tags: Array<any> | null;
    recipe: Colame.Item.Data.RecipeData | null;
    currentPrice: Colame.Item.Data.ItemLocationPriceData | null;
    childItems: Array<any> | null;
    stockInfo: Colame.Item.Data.ItemLocationStockData | null;
  };
  export type ModifierGroupData = {
    id: number | null;
    name: string;
    description: string | null;
    selectionType: string;
    isRequired: boolean;
    minSelections: number;
    maxSelections: number | null;
    isActive: boolean;
    createdAt: string | null;
    updatedAt: string | null;
    deletedAt: string | null;
  };
  export type ModifierGroupWithModifiersData = {
    modifierGroup: Colame.Item.Data.ModifierGroupData;
    modifiers: Array<any>;
    sortOrder: number;
  };
  export type ModifierPriceImpactData = {
    modifierId: number;
    modifierName: string;
    modifierGroupId: number;
    modifierGroupName: string;
    quantity: number;
    unitPrice: number;
    priceImpact: number;
  };
  export type PriceCalculationData = {
    itemId: number;
    variantId: number | null;
    locationId: number | null;
    basePrice: number;
    variantAdjustment: number;
    modifierAdjustments: Array<any>;
    locationPrice: number | null;
    subtotal: number;
    total: number;
    currency: string;
    appliedRules: Array<any>;
  };
  export type RecipeData = {
    id: number | null;
    itemId: number;
    itemVariantId: number | null;
    instructions: string;
    prepTimeMinutes: number;
    cookTimeMinutes: number;
    yieldQuantity: number;
    yieldUnit: string;
    notes: string | null;
    ingredients: Array<any> | null;
    totalCost: number | null;
    costPerUnit: number | null;
    createdAt: string | null;
    updatedAt: string | null;
  };
  export type RecipeIngredientData = {
    id: number | null;
    recipeId: number;
    ingredientId: number;
    quantity: number;
    unit: string;
    isOptional: boolean;
    ingredient: Colame.Item.Data.IngredientData | null;
  };
  export type StockAlertData = {
    itemId: number;
    variantId: number | null;
    locationId: number | null;
    itemName: string;
    currentQuantity: number;
    minQuantity: number;
    alertType: string;
    suggestedReorderQuantity: number | null;
  };
}
declare namespace Colame.Order.Data {
  export type CreateOrderData = {
    userId: number | null;
    locationId: number;
    type: string;
    tableNumber: number | null;
    customerName: string | null;
    customerPhone: string | null;
    customerEmail: string | null;
    deliveryAddress: string | null;
    items: any;
    notes: string | null;
    specialInstructions: string | null;
    offerCodes: Array<any> | null;
    metadata: Array<any> | null;
  };
  export type CreateOrderItemData = {
    item_id: number;
    quantity: number;
    unit_price: number;
    notes: string | null;
    modifiers: Array<any> | null;
    metadata: Array<any> | null;
  };
  export type OrderData = {
    id: number;
    orderNumber: string;
    userId: number | null;
    locationId: number;
    status: string;
    type: string;
    priority: string;
    subtotal: number;
    taxAmount: number;
    tipAmount: number;
    discountAmount: number;
    totalAmount: number;
    paymentStatus: string;
    customerName: string | null;
    customerPhone: string | null;
    customerEmail: string | null;
    deliveryAddress: string | null;
    tableNumber: number | null;
    waiterId: number | null;
    notes: string | null;
    specialInstructions: string | null;
    cancelReason: string | null;
    metadata: Array<any> | null;
    items: any | null;
    placedAt: string | null;
    confirmedAt: string | null;
    preparingAt: string | null;
    readyAt: string | null;
    deliveringAt: string | null;
    deliveredAt: string | null;
    completedAt: string | null;
    cancelledAt: string | null;
    scheduledAt: string | null;
    createdAt: string | null;
    updatedAt: string | null;
  };
  export type OrderItemData = {
    id: number;
    orderId: number;
    itemId: number;
    itemName: string;
    quantity: number;
    unitPrice: number;
    totalPrice: number;
    status: string;
    kitchenStatus: string;
    course: string | null;
    notes: string | null;
    modifiers: Array<any> | null;
    metadata: Array<any> | null;
    preparedAt: string | null;
    servedAt: string | null;
    createdAt: string | null;
    updatedAt: string | null;
  };
  export type OrderStatusHistoryData = {
    id: number;
    orderId: number;
    fromStatus: string;
    toStatus: string;
    userId: number | null;
    reason: string | null;
    metadata: Array<any> | null;
    createdAt: string | null;
  };
  export type OrderWithRelationsData = {
    order: Colame.Order.Data.OrderData;
    user: object | null;
    location: object | null;
    payments: Array<any> | null;
    offers: Array<any> | null;
  };
  export type PaymentTransactionData = {
    id: number;
    orderId: number;
    method: string;
    amount: number;
    status: string;
    referenceNumber: string | null;
    processorResponse: Array<any> | null;
    processedAt: string | null;
    createdAt: string | null;
    updatedAt: string | null;
  };
  export type UpdateOrderData = {
    notes: any | string;
    customerName: any | string;
    customerPhone: any | string;
    metadata: any | Array<any>;
    items: any | Array<any>;
  };
}
